#!/usr/bin/env node
// Site build: syncs shared regions into every page and regenerates docs/SITE.md.
//
//   node scripts/build.mjs            write changes
//   node scripts/build.mjs --check    exit 1 if any file is out of date or any page/doc link is broken (CI)
//   node scripts/build.mjs new <slug> "<Title>" [--nav "<Label>"]
//
// Pages are plain HTML served as-is by GitHub Pages. Anything between
// <!-- build:NAME --> and <!-- /build:NAME --> is owned by this script and
// rendered from partials/NAME.html. Edit the partial, never the region.

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const configPath = join(root, 'site.config.json');
const config = JSON.parse(readFileSync(configPath, 'utf8'));
const REGIONS = ['head', 'header', 'footer'];
const DOCS = 'docs/SITE.md';

const read = (p) => readFileSync(join(root, p), 'utf8');
const escapeHtml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const stripTags = (s) => s.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();

// Replaces {{key}} placeholders. Multi-line values are indented to match the placeholder's line.
function fill(template, vars) {
  return template.replace(/^([ \t]*)(.*)$/gm, (line, indent) =>
    line.replace(/\{\{(\w+)\}\}/g, (m, key) => {
      if (!(key in vars)) throw new Error(`Unknown placeholder ${m}`);
      return vars[key].split('\n').join(`\n${indent}`);
    }));
}

function pageMeta(file, html) {
  const pick = (re) => (html.match(re) || [])[1];
  return {
    file,
    title: stripTags(pick(/<title>([\s\S]*?)<\/title>/) || ''),
    description: pick(/<meta name="description" content="([^"]*)"/) || '',
    h1: stripTags(pick(/<h1[^>]*>([\s\S]*?)<\/h1>/) || ''),
    sections: [...html.matchAll(/<h2[^>]*>([\s\S]*?)<\/h2>/g)].map((m) => stripTags(m[1])),
  };
}

function navLinks(file, cls) {
  return config.nav.map((item) => {
    const current = item.href === file ? ' aria-current="page"' : '';
    return `<a class="${cls}" href="${item.href}"${current}>${escapeHtml(item.label)}</a>`;
  }).join('\n');
}

function renderRegion(name, meta) {
  const { site, cta } = config;
  const canonicalPath = meta.file === 'index.html' ? '' : meta.file;
  return fill(read(`partials/${name}.html`), {
    title: escapeHtml(meta.title),
    description: meta.description,
    canonical: `${site.url}/${canonicalPath}`,
    nav: navLinks(meta.file, 'nav__link'),
    ctaLabel: escapeHtml(cta.label),
    ctaHref: cta.href,
    ctaCurrent: cta.href === meta.file ? ' aria-current="page"' : '',
    siteName: escapeHtml(site.name),
    email: site.email,
    linkedin: site.linkedin,
    location: escapeHtml(site.location),
    year: String(new Date().getFullYear()),
  }).trimEnd();
}

function syncPage(file, html) {
  const meta = pageMeta(file, html);
  for (const name of REGIONS) {
    const re = new RegExp(`([ \\t]*)<!-- build:${name} -->[\\s\\S]*?<!-- /build:${name} -->`);
    const match = html.match(re);
    if (!match) throw new Error(`${file}: missing <!-- build:${name} --> region`);
    const indent = match[1];
    const body = renderRegion(name, meta).split('\n').map((l) => (l ? indent + l : l)).join('\n');
    html = html.replace(re, () => `${indent}<!-- build:${name} -->\n${body}\n${indent}<!-- /build:${name} -->`);
  }
  return html;
}

function renderRedirect(target) {
  return fill(read('partials/redirect.html'), { target, canonical: `${config.site.url}/${target}` });
}

function renderDocs(pages) {
  const rows = pages.map((p) => {
    const inNav = config.nav.find((n) => n.href === p.file);
    return `| [${p.file}](../${p.file}) | ${p.h1} | ${inNav ? inNav.label : '—'} | ${p.description} |`;
  });
  const outlines = pages.map((p) => `### ${p.file} — ${p.title}\n\n${p.sections.map((s) => `- ${s}`).join('\n') || '- (no h2 sections)'}`);
  const redirects = Object.entries(config.redirects).map(([from, to]) => `| ${from} | ${to} |`);
  return `<!-- GENERATED by scripts/build.mjs from the HTML pages and site.config.json. Do not edit by hand. -->

# Site map

${pages.length} pages. Navigation order: ${config.nav.map((n) => n.label).join(' → ')}, then the "${config.cta.label}" button (${config.cta.href}).

| File | Heading (h1) | Nav label | Meta description |
|---|---|---|---|
${rows.join('\n')}

## Page outlines (h2 sections)

${outlines.join('\n\n')}

## Redirect stubs

Old URLs kept alive so existing links don't break. Generated from \`redirects\` in site.config.json.

| From | To |
|---|---|
${redirects.join('\n')}

## Shared regions

Every page contains these build regions, rendered from \`partials/<name>.html\`: ${REGIONS.map((r) => `\`${r}\``).join(', ')}.
`;
}

// Every relative Markdown link in the agent docs (standards/, prompts/, .github/ …) must
// point at a file that exists, so instructions can't silently drift from the repo.
function checkDocLinks() {
  const broken = [];
  const mdFiles = readdirSync(root, { recursive: true })
    .filter((f) => f.endsWith('.md') && !f.split(/[\\/]/).some((part) => part === 'node_modules' || part === '.git'));
  for (const file of mdFiles) {
    const text = readFileSync(join(root, file), 'utf8').replace(/```[\s\S]*?```/g, '');
    for (const [, target] of text.matchAll(/\]\(([^)\s]+)\)/g)) {
      if (/^([a-z]+:|#)/.test(target)) continue;
      if (!existsSync(join(root, dirname(file), target.split('#')[0]))) broken.push(`${file} → ${target}`);
    }
  }
  if (broken.length) throw new Error(`Broken doc links:\n  ${broken.join('\n  ')}`);
}

function build({ check }) {
  const outputs = new Map();
  const pages = [];
  const files = readdirSync(root).filter((f) => f.endsWith('.html')).sort((a, b) =>
    a === 'index.html' ? -1 : b === 'index.html' ? 1 : a.localeCompare(b));

  for (const file of files) {
    if (file in config.redirects) continue;
    const html = syncPage(file, read(file));
    outputs.set(file, html);
    pages.push(pageMeta(file, html));
  }
  for (const [from, to] of Object.entries(config.redirects)) outputs.set(from, renderRedirect(to));
  // Every local link (href="x.html", "x.html#id", "assets/...") must resolve to a real file.
  const broken = [];
  for (const [file, html] of outputs) {
    for (const [, href] of html.matchAll(/(?:href|src)="(?![a-z]+:|\/\/)([^"#?]+)[^"]*"/g)) {
      if (!outputs.has(href) && !existsSync(join(root, href))) broken.push(`${file} → ${href}`);
    }
  }
  if (broken.length) throw new Error(`Broken local links:\n  ${broken.join('\n  ')}`);
  checkDocLinks();
  outputs.set(DOCS, renderDocs(pages));

  const stale = [];
  for (const [file, content] of outputs) {
    const path = join(root, file);
    if (existsSync(path) && readFileSync(path, 'utf8') === content) continue;
    stale.push(file);
    if (!check) writeFileSync(path, content);
  }
  if (check && stale.length) {
    console.error(`Out of date: ${stale.join(', ')}\nRun: node scripts/build.mjs`);
    process.exit(1);
  }
  console.log(stale.length ? `${check ? 'Stale' : 'Updated'}: ${stale.join(', ')}` : 'Everything up to date.');
}

function newPage(slug, title, navLabel) {
  if (!slug || !title) throw new Error('Usage: node scripts/build.mjs new <slug> "<Title>" [--nav "<Label>"]');
  const file = `${slug.replace(/\.html$/, '')}.html`;
  if (existsSync(join(root, file))) throw new Error(`${file} already exists`);
  writeFileSync(join(root, file), fill(read('partials/page-template.html'), { title: escapeHtml(title) }));
  if (navLabel) {
    config.nav.push({ label: navLabel, href: file });
    writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');
  }
  console.log(`Created ${file}${navLabel ? ` and added "${navLabel}" to the nav` : ''}.`);
  build({ check: false });
}

const [cmd, ...rest] = process.argv.slice(2);
try {
  if (cmd === 'new') {
    const navIdx = rest.indexOf('--nav');
    const navLabel = navIdx >= 0 ? rest.splice(navIdx, 2)[1] : undefined;
    newPage(rest[0], rest[1], navLabel);
  } else {
    build({ check: cmd === '--check' });
  }
} catch (err) {
  console.error(err.message);
  process.exit(1);
}
